### PR TITLE
Gracefully handling removal of Test resource outside terraform

### PR DESCRIPTION
**Pull request by ziemowit141**
It might seem, like a small change but produces beautifull results.

Instead of:

> piotr@piotr-ThinkPad-E595:~/Projects/kentik/terraform-provider-kentik-synthetics/examples/resources/kentik-synthetics_test$ terraform apply
kentik-synthetics_test.example-hostname-test: Refreshing state... [id=3]
╷
│ Error: failed to read test
│ 
│   with kentik-synthetics_test.example-hostname-test,
│   on resource.tf line 1, in resource "kentik-synthetics_test" "example-hostname-test":
│    1: resource "kentik-synthetics_test" "example-hostname-test" {
│ 
│ error: 404 Not Found, status: 404 Not Found, body: {{"code":2,"message":"test GET failed: no such test \"3\""}
│ }

We get:

> piotr@piotr-ThinkPad-E595:~/Projects/kentik/terraform-provider-kentik-synthetics/examples/resources/kentik-synthetics_test$ terraform apply
kentik-synthetics_test.example-hostname-test: Refreshing state... [id=3]
Note: Objects have changed outside of Terraform
Terraform detected the following changes made outside of Terraform since the last "terraform apply":
... missing resource ...
Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan
may include actions to undo or respond to these changes.

### CODE REVIEW

**Comment by ziemowit141** [comment]
https://clkentik.atlassian.net/browse/KNTK-298

**Review by mmac-m3a — APPROVED** [review]
The logic looks right. Mismatch between TF state and actual state of the resource is a normal runtime state and should not be reported as an error.

**Comment by mmac-m3a** [comment]
Will merge after @Fenthick approves the PR.

**Review by Fenthick — APPROVED** [review]

**Comment by Fenthick** [comment]
@ziemowit141 Could you do the same in Cloud Export?

**Pull request merged**
