### PR TITLE
Upgrade Kentik API client and minor improvements

### PR DESCRIPTION
**Pull request by Fenthick**
Additional improvements:
- rename debug flag to log_paylods to make this flag clearly
  separate from TF_LOG=debug environment variable
- improve README.md
- upgrade golangci-lint
- upgrade github.com/hashicorp/terraform-plugin-sdk/v2
- regenerate the documentation

Issue: https://clkentik.atlassian.net/browse/KNTK-333

### CODE REVIEW

**Review by Opelord — APPROVED** [review]
Looks good to me

**Review by mmac-m3a — APPROVED** [review]
LGTM

**Comment by mmac-m3a** [comment]
Waiting for @Fenthick to approve.

**Comment by mmac-m3a** [comment]
Waiting for @Opelord to approve.

**Review by Opelord — APPROVED** [review]
LGTM

**Pull request merged**
