### PR TITLE
Changed log. to tflog. package

### PR DESCRIPTION
**Pull request by jdziurzynski**
KNTK - 262
It looks like a terrafrom core look up for TF_LOG environment variable by default, so I only changed the current way of logging to use tflog package.

### CODE REVIEW

**Review by mmac-m3a — COMMENTED** [review]
Is this really all? Will it make all messages related to interactions with Kentik API appear in logs?

**Comment by jdziurzynski** [comment]
If TF_LOG environment variable will be set, I think yes.

**Comment by jdziurzynski** [comment]
> Is this really all? Will it make all messages related to interactions with Kentik API appear in logs?

If TF_LOG environment variable will be set, I think yes.

**Comment by mmac-m3a** [comment]
Can you, please, show me example debug output? I'd like to see what information we can provide and how are API requests and responses represented in the output.

**Comment by jdziurzynski** [comment]
Here https://pastebin.com/mjzcvf6E You can find debug output for example from kentik-synthetic_test. TF_LOG were set to TRACE.

**Review by danielfurman — APPROVED** [review]

**Comment by mmac-m3a** [comment]
Thanks for the debug output. I'll approve and merge this PR. However, in order to close ticker KNTK-262 we need to add logging of API requests and responses (at debug level) to the provider.

**Review by mmac-m3a — APPROVED** [review]

**Pull request merged**
